"""empty message

Revision ID: fd452e8b0dd2
Revises: 
Create Date: 2017-02-24 16:15:10.372271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd452e8b0dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('cuisine_type', sa.String(length=50), nullable=True),
    sa.Column('opening_time', sa.String(length=15), nullable=True),
    sa.Column('closing_time', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_address'), 'store', ['address'], unique=True)
    op.create_index(op.f('ix_store_store_name'), 'store', ['store_name'], unique=True)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=30), nullable=True),
    sa.Column('price', sa.String(length=15), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_item_name'), 'item', ['item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_table('menu')
    op.drop_index(op.f('ix_store_store_name'), table_name='store')
    op.drop_index(op.f('ix_store_address'), table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
